<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
  MessageDefinition.xml : メッセージ定義ファイル

  Copyright (c) 2003, 2023 Ricoh Company, Ltd.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
   
      http://www.apache.org/licenses/LICENSE-2.0
   
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!DOCTYPE MessageDefine [
  <!ELEMENT MessageDefine (Message)*>

  <!ELEMENT Message (Name, Number, Format, Argument*)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Number (#PCDATA)>

  <!ELEMENT Format (English, Japanese)>
  <!ELEMENT Argument (#PCDATA)>

  <!ELEMENT English (#PCDATA)>
  <!ELEMENT Japanese (#PCDATA)>
]>

<!--
★メッセージ定義に関する注意★

	【メッセージ定義ファイル自体について】
		・ファイルの文字コードを SJIS から変更してはいけない

	【メッセージ作成の方針について】

	【メッセージ番号について】
		・Number は16 進8 桁で定義し、

		  上位 2 桁は 0x01
		  次の 2 桁は モジュールを識別する値
		  下位 4 桁は モジュール内でのメッセージを一意に識別する値
		
		  にすること
		・決して、Exception/ErrorDefinition.xml の
		  エラー番号と重なってはならない

	【フォーマットについて】
		・日本語メッセージは「ですます」調で統一すること
		・Format に %1 などで挿入されるものが文字列である場合、
		  できる限り言語に左右されない文字列
		  (SQL 文、表名、数値など)にすること
-->

<MessageDefine>

  <Message>
    <Name>VerifyFailed</Name>
	<Number>0x01370001</Number>
	<Format>
	  <English>Verification has been failed.</English>
	  <Japanese>整合性検査に失敗しました。</Japanese>
	</Format>
  </Message>

  <Message>
    <Name>IllegalRootPageID</Name>
	<Number>0x01370002</Number>
	<Format>
	  <English>The root page id is inconsistent.</English>
	  <Japanese>ルートページIDが不正です。</Japanese>
	</Format>
  </Message>

  <Message>
    <Name>IllegalLeftLeafPageID</Name>
	<Number>0x01370003</Number>
	<Format>
	  <English>The left leaf page id is inconsistent.</English>
	  <Japanese>左端のリーフページIDが不正です。</Japanese>
	</Format>
  </Message>

  <Message>
    <Name>IllegalRightLeafPageID</Name>
	<Number>0x01370004</Number>
	<Format>
	  <English>The right leaf page id is inconsistent.</English>
	  <Japanese>右端のリーフページIDが不正です。</Japanese>
	</Format>
  </Message>

  <Message>
    <Name>DiscordKeyNum</Name>
	<Number>0x01370005</Number>
	<Format>
	  <English>The number of objects in file is inconsistent with number of key in leaf page. (object=%1, key=%2)</English>
	  <Japanese>ファイルヘッダに書かれたオブジェクト数とリーフページのキー数が一致しません。(object=%1, key=%2)</Japanese>
	</Format>
	<Argument>%d</Argument>
	<Argument>%d</Argument>
  </Message>

  <Message>
    <Name>DiscordDelegateKey</Name>
	<Number>0x01370006</Number>
	<Format>
	  <English>Delegate key in parent node is inconsistent with delegate key in child node. (parentpage=%1, childpage=%2)</English>
	  <Japanese>親ノードと子ノードの代表キーが一致しません。(parentpage=%1, childpage=%2)</Japanese>
	</Format>
	<Argument>%d</Argument>
	<Argument>%d</Argument>
  </Message>

  <Message>
    <Name>IllegalKeyIndex</Name>
	<Number>0x01370007</Number>
	<Format>
	  <English>Key information index is inconsistent. (page=%1, keynum=%2)</English>
	  <Japanese>キー情報のインデックスが矛盾しています。(page=%1, keynum=%2)</Japanese>
	</Format>
	<Argument>%d</Argument>
	<Argument>%d</Argument>
  </Message>

</MessageDefine>

<!--
  Copyright (c) 2003, 2023 Ricoh Company, Ltd.
  All rights reserved.
-->
