<?xml version="1.0" encoding="UTF-8" standalone="yes"?>

<!--
  ExceptionMaster.xml : 例外クラスのもとになるエラー定義ファイル

  Copyright (c) 2000, 2014, 2023 Ricoh Company, Ltd.

  Licensed under the Apache License, Version 2.0 (the "License");
  you may not use this file except in compliance with the License.
  You may obtain a copy of the License at
   
      http://www.apache.org/licenses/LICENSE-2.0
   
  Unless required by applicable law or agreed to in writing, software
  distributed under the License is distributed on an "AS IS" BASIS,
  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  See the License for the specific language governing permissions and
  limitations under the License.
-->

<!DOCTYPE ErrorDefine [
  <!ELEMENT ErrorDefine (Error)*>

  <!ELEMENT Error (Name, Number, StateCode, Message, MessageArgument*, Description, Solution, Alias*, Convert)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Number (#PCDATA)>
  <!ELEMENT StateCode (#PCDATA)>

  <!ELEMENT Message (English, Japanese)>
  <!ELEMENT MessageArgument (#PCDATA)>
  <!ELEMENT Description (English?, Japanese)>
  <!ELEMENT Solution (English?, Japanese)>
  <!ELEMENT Alias (#PCDATA)>
  <!ELEMENT Convert (#PCDATA)>

  <!ELEMENT English (#PCDATA)>
  <!ELEMENT Japanese (#PCDATA)>
]>

<!--
★エラー定義に関する注意★

	【エラー定義ファイル自体について】
		・ファイルの文字コードをSJISから変更してはいけない
		・定義は共通のものとCommon、セッションなどモジュールごとの
		  セクションに分かれる
		・セクションわけはNumberの衝突を防ぐことが目的であり、
		  ほかのモジュールに対応するセクションの例外は使えないなどの制限はない

	【例外作成の方針について】
		・例外の種類はなるべく増やさない、必要なら詳細をログに出す

	【エラー番号について】
		・0番のエラーは作ってはいけない
		・Numberは16進8桁で定義し、上位4桁はセクションごとに決まる値を使う

	【エラーレベルについて】
		・エラーレベルはUserとSystemの2種類
		・Userレベルの例外はユーザのオペミス等、ユーザの操作に起因するエラー
		・Systemレベルの例外はシステムの状態に起因する例外
		・Userレベルの例外が発生しても使用していたコネクションは破棄しない

	【エラーメッセージについて】
		・Messageに%1などで挿入されるものが文字列である場合、
		  言語に左右されない文字列(SQL文、表名など)のみがあてはまるようにする
		  補足説明などの「文」を挿入するようにしてはいけない
		・ユーザーエラーと非ユーザーエラーを完全に区別することはできないが、
		  あきらかに非ユーザーエラーであるばあいは日本語メッセージの先頭に
		  「内部エラー:」をつける

-->

<ErrorDefine>

<!--
SQLSTATEに対応したクラス(0x1000)
-->

<!-- 00 S successful completion(0x10000000) -->
<!-- 01 W warning(0x10000100) -->
<!-- 02 N no data(0x10000200) -->
<!-- 03 X SQL statement not yet complete(0x10000300) -->

<!-- 07 X dynamic SQL error(0x10000400) -->
<!-- 07001 using clause does not match dynamic parameter specifications(0401) -->

  <Error>
    <Name>DynamicParameterNotMatch</Name>
    <Number>0x10000401</Number>
    <StateCode>07001</StateCode>
    <Level>User</Level>
    <Message>
      <English>The number of parameter values(%1) does not match parameters(%2).</English>
      <Japanese>パラメーター値の数(%1)が必要な数(%2)と一致しません。</Japanese>
    </Message>
    <MessageArgument>%d</MessageArgument>
    <MessageArgument>%d</MessageArgument>
    <Description>
      <Japanese>
      	?を用いたSQL文に対して必要な数のパラメーターが指定されていない
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
      	必要な数のパラメーターを指定する
      </Japanese>
    </Solution>
  </Error>

<!-- 07002 using clause does not match target specifications -->
<!-- 07003 cursor specification cannot be executed -->
<!-- 07004 using clause required for dynamic parameters -->
<!-- 07005 prepared statement not a cursor specification -->
<!-- 07006 restricted data type attribute violation -->
<!-- 07007 using clause required for result fields -->
<!-- 07008 invalid descriptor count -->
<!-- 07009 invalid descriptor index -->
<!-- 0700B data type transform function violation -->
<!-- 0700C undefined DATA value -->
<!-- 0700D invalid DATA target -->
<!-- 0700F invalid DATETIME_INTERVAL_CODE -->
<!-- 0700E invalid LEVEL value -->

<!-- 08 X connection exception(0x10000500) -->
<!-- 08000 (no subclass) -->
<!-- 08001 SQL-client unable to establish SQL-connection(0501) -->
<!-- 08002 connection name in use(0502) -->
<!-- 08003 connection does not exist(0503) -->
  <Error>
    <Name>ConnectionNotExist</Name>
    <Number>0x10000503</Number>
    <StateCode>08003</StateCode>
    <Level>System</Level>
    <Message>
      <English>Connection exception - connection does not exist.</English>
      <Japanese>指定されたセッションが存在しません。</Japanese>
    </Message>
    <Description>
      <Japanese>
      	存在しないセッションIDが渡された
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	正しいセッションIDを使用する
      </Japanese>
    </Solution>
  </Error>
<!-- 08003 client not exist(0508) -->
  <Error>
    <Name>ClientNotExist</Name>
    <Number>0x10000508</Number>
    <StateCode>08003</StateCode>
    <Level>System</Level>
    <Message>
      <English>Connection exception - client(ID=%1) does not exist.</English>
      <Japanese>指定されたクライアント(ID=%1)が存在しません。</Japanese>
    </Message>
    <MessageArgument>%d</MessageArgument>
    <Description>
      <Japanese>
      	存在しないクライアントIDが渡された
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	正しいクライアントIDを使用する
      </Japanese>
    </Solution>
  </Error>
<!-- 08003 client not exist(0509) -->
  <Error>
    <Name>SessionNotExist</Name>
    <Number>0x10000509</Number>
    <StateCode>08003</StateCode>
    <Level>System</Level>
    <Message>
      <English>Connection exception - session(ID=%1) does not exist.</English>
      <Japanese>指定されたセッション(ID=%1)が存在しません。</Japanese>
    </Message>
    <MessageArgument>%d</MessageArgument>
    <Description>
      <Japanese>
      	存在しないセッションIDが渡された
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	正しいセッションIDを使用する
      </Japanese>
    </Solution>
  </Error>

<!-- 08004 SQL-server rejected establishment of SQL-connection(0504) -->
<!-- 08006 connection failure(0506) -->
<!-- 08007 transaction resolution unknown(0507) -->

<!-- *************** SYSTEM DEFINED ****************** -->
<!-- 08501 authorization failed(0551) -->
  <Error>
    <Name>AuthorizationFailed</Name>
    <Number>0x10000551</Number>
    <StateCode>08501</StateCode>
    <Level>User</Level>
    <Message>
      <English>Connection exception - authorization failed.</English>
      <Japanese>認証に失敗しました。</Japanese>
    </Message>
    <Description>
      <Japanese>
	正しくないパスワードが指定された
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	正しいパスワードを指定する
      </Japanese>
    </Solution>
  </Error>

<!-- 09 X triggered action exception(0x10000600) -->

<!-- 0A X feature not supported(0x10000700) -->
  <Error>
    <Name>NotSupported</Name>
    <!-- not supportedはv14以前からあるので番号は昔のものを使う -->
    <Number>0x00000005</Number>
    <StateCode>0A000</StateCode>
    <Level>User</Level>
    <Message>
      <English>Feature not supported.</English>
      <Japanese>サポートされていない機能を使用しました。</Japanese>
    </Message>
    <Description>
      <Japanese>実装されていない機能を使用しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>
	その機能を使用しないようにする
      </Japanese>
    </Solution>
  </Error>

  <Error>
    <Name>FullTextIndexNeeded</Name>
    <Number>0x10000751</Number>
    <StateCode>0A501</StateCode>
    <Level>User</Level>
    <Message>
      <English>Fulltext index is needed.</English>
      <Japanese>全文索引が定義されている必要があります。</Japanese>
    </Message>
    <Description>
      <Japanese>全文索引が定義されていないのに全文索引が必要な機能を使用しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>
	全文索引を定義するか、その機能を使用しないようにする
      </Japanese>
    </Solution>
  </Error>

  <Error>
    <Name>SpatialIndexNeeded</Name>
    <Number>0x10000752</Number>
    <StateCode>0A502</StateCode>
    <Level>User</Level>
    <Message>
      <English>Spatial index is needed.</English>
      <Japanese>空間索引が定義されている必要があります。</Japanese>
    </Message>
    <Description>
      <Japanese>空間索引が定義されていないのに空間索引が必要な機能を使用しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>
	空間索引を定義するか、その機能を使用しないようにする
      </Japanese>
    </Solution>
  </Error>

<!-- 0B X invalid transaction initiation(0x10000800) -->
<!-- 0D X invalid target type specification(0x10000900) -->
<!-- 0E X invalid schema name list specification(0x10000a00) -->
<!-- 0F X locator exception(0x10000b00) -->
<!-- 0L X invalid grantor(0x10000c00) -->
<!-- 0M X invalid SQL-invoked procedure reference(0x10000d00) -->
<!-- 0P X invalid role specification(0x10000e00) -->

<!-- *************** SYSTEM DEFINED ****************** -->
<!-- 0P501 no such role -->
  <Error>
    <Name>RoleNotFound</Name>
    <Number>0x10000e51</Number>
    <StateCode>0P501</StateCode>
    <Level>User</Level>
    <Message>
      <English>Invalid role specification - role '%1' is not found.</English>
      <Japanese>ロール'%1'は登録されていません。</Japanese>
    </Message>
    <MessageArgument>%s</MessageArgument>
    <Description>
      <Japanese>
	指定されたロールが登録されていない
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	登録されているロールを指定する
      </Japanese>
    </Solution>
  </Error>

<!-- 0S X invalid transform group name specification(0x10000f00) -->
<!-- 0T X target table diagrees with cursor specification(0x10001000) -->
<!-- 0T X target table diagrees with cursor specification(0x10001100) -->
<!-- 0U X attempt to assign to non-updatable column(0x10001200) -->
<!-- 0U X attempt to assign to ordering column(0x10001300) -->
<!-- 0W X attempt to assign to ordering column(0x10001400) -->
<!-- 0Z X diagnostics exception(0x10001500) -->

<!-- 21 X cardinality violation(0x10001600) -->
  <Error>
    <Name>CardinalityViolation</Name>
    <Number>0x10001601</Number>
    <StateCode>21000</StateCode>
    <Level>User</Level>
    <Message>
      <English>Cardinality violation.</English>
      <Japanese>単一行のみ許される問い合わせが2行以上返しています。</Japanese>
    </Message>
    <Description>
      <Japanese>row subqueryにあたる場所で結果が2行以上だった</Japanese>
    </Description>
    <Solution>
      <Japanese>
        問い合わせを確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 22 X data exception(0x10001700) -->

<!-- 22000 (no subclass)(1701) -->
<!-- 22001 string data, right truncation(1702) -->
  <Error>
    <Name>StringRightTruncation</Name>
    <Number>0x10001702</Number>
    <StateCode>22001</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - string data, right truncation.</English>
      <Japanese>文字列型へのキャストで制限長を超える部分があります。</Japanese>
    </Message>
    <Description>
      <Japanese>制限長のある文字列型へのキャストで制限長を超える部分があった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        制限長が十分か確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 22002 null value, no indicator parameter(1703) -->

<!-- 22003 numeric value out of range(1704) -->
  <Error>
    <Name>NumericValueOutOfRange</Name>
    <Number>0x10001704</Number>
    <StateCode>22003</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - numeric value out of range.</English>
      <Japanese>数値型の演算で範囲を超える操作をしようとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>四則演算などの結果数値型で表現できる範囲を超える操作があった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        超えないようにする
      </Japanese>
    </Solution>
  </Error>

<!-- 22004 null value not allowed(1705) -->
  <Error>
    <Name>NullNotAllowed</Name>
    <Number>0x10001705</Number>
    <StateCode>22004</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - null value not allowed.</English>
      <Japanese>ナル値が許されない操作をしようとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>ナル値が許されない操作をした。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        ナル値になった操作を確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 22005 error in assignment(1706) -->
<!-- 22006 invalid interval format(1707) -->

<!-- 22007 invalid datetime format(1708) -->
  <Error>
    <Name>InvalidDatetimeFormat</Name>
    <Number>0x10001708</Number>
    <StateCode>22007</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - invalid datetime format.</English>
      <Japanese>日時型に変換できません。</Japanese>
    </Message>
    <Description>
      <Japanese>日時型へのキャストで日時型に変換できない文字列が渡された。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        キャストしようとした値を確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 22008 datetime field overflow(1709) -->
<!-- 22009 invalid time zone displacement value(170a) -->
<!-- 2200B escape character conflict(170b) -->
<!-- 2200C invalid use of escape character(170c) -->
<!-- 2200D invalid escape octet(170d) -->

<!-- 2200E null value in array target(170E) -->
<!-- 配列への代入はサポートしていない
  <Error>
    <Name>NullInArray</Name>
    <Number>0x1000170E</Number>
    <StateCode>2200E</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - null value in array target.</English>
      <Japanese>nullの配列要素には代入できません。</Japanese>
    </Message>
    <Description>
      <Japanese>配列型の要素への代入が指示されたが対象がnullだった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        代入対象がnullでないようにする
      </Japanese>
    </Solution>
  </Error>
-->

<!-- 2200F zero-length character string(170f) - Sydneyではエラーにしない -->
<!-- 2200G most specific type mismatch(1710) -->

<!-- 2200H sequence generator limit exceeded(1711) -->
  <Error>
    <Name>SequenceLimitExceeded</Name>
    <Number>0x10001711</Number>
    <StateCode>2200H</StateCode>
    <Level>System</Level>
    <Message>
      <English>Data exception - sequence generator limit exceeded.</English>
      <Japanese>シーケンスの値が最大値に到達しました。</Japanese>
    </Message>
    <Description>
      <Japanese>シーケンスの値が最大値になった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        これ以上挿入できない。
      </Japanese>
    </Solution>
  </Error>

<!-- 2200P interval value out of range(1712) -->
<!-- 2200Q multiset value overflow(1713) -->
<!-- 22010 invalid indicator parameter value(1714) -->

<!-- 22011 substring error(1715) -->
  <Error>
    <Name>SubStringError</Name>
    <Number>0x10001715</Number>
    <StateCode>22011</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - substring error.</English>
      <Japanese>SUBSTRINGの引数が不正です。</Japanese>
    </Message>
    <Description>
      <Japanese>SUBSTRINGでstart positionが長さを超えていた。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        SUBSTRINGの引数を確認する。
      </Japanese>
    </Solution>
  </Error>

<!-- 22012 division by zero(1716) -->
  <Error>
    <Name>DivisionByZero</Name>
    <Number>0x10001716</Number>
    <StateCode>22012</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - division by zero.</English>
      <Japanese>0による除算をしようとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>割り算のdivisorが0だった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        0で割らないようにする。
      </Japanese>
    </Solution>
  </Error>

<!-- 22013 invalid preceding or following size in window function(1717) -->
<!-- 22015 interval field overflow(1718) -->

<!-- 22018 invalid character value for cast(1719) -->
  <Error>
    <Name>InvalidCharacter</Name>
    <Number>0x10001719</Number>
    <StateCode>22018</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - invalid character value for cast.</English>
      <Japanese>文字列の中にキャストできない文字が含まれています。</Japanese>
    </Message>
    <Description>
      <Japanese>文字列型をキャストするときにターゲットの型に対して不正な文字が含まれていた。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        キャストしようとした文字列を確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 22019 invalid escape character(171a) -->
  <Error>
    <Name>InvalidEscape</Name>
    <Number>0x1000171a</Number>
    <StateCode>22019</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - invalid escape character.</English>
      <Japanese>エスケープ文字は1文字でなければなりません。</Japanese>
    </Message>
    <Description>
      <Japanese>LikeやSimilarに指定したエスケープ文字の長さが1でなかった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        エスケープ文字の内容を確認する
      </Japanese>
    </Solution>
  </Error>

<!-- 2201B invalid regular expression(171b) -->
  <Error>
    <Name>InvalidRegularExpression</Name>
    <Number>0x1000171b</Number>
    <StateCode>2201B</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - invalid regular expression.</English>
      <Japanese>正規表現が正しくありません。</Japanese>
    </Message>
    <Description>
      <Japanese>Similarに指定した正規表現が正しくない。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        正規表現を正しくする
      </Japanese>
    </Solution>
  </Error>

<!-- 2201C null row not permitted in table(171c) -->
<!--
  <Error>
    <Name>NullRowNotPermitted</Name>
    <Number>0x1000171c</Number>
    <StateCode>2201c</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - null row not permitted in table.</English>
      <Japanese>VALUESを構成する行にnullが含まれています。</Japanese>
    </Message>
    <Description>
      <Japanese>table value constructorを構成する行にnullがあった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        table value constructorを構成する行にnullを書かない
      </Japanese>
    </Solution>
  </Error>
-->

<!-- 2201E invalid argument for natural logarithm(171d) -->
<!-- 2201F invalid argument for power function(171e) -->
<!-- 2201G invalid argument for width bucket function(171f) -->

  <Error>
  <!-- 22021 character not in repertoire(1720) -->
    <Name>CharacterNotInRepertoire</Name>
    <Number>0x10001720</Number>
    <StateCode>22021</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - character not in repertoire.</English>
      <Japanese>型が対応していない文字を指定しています。</Japanese>
    </Message>
    <Description>
      <Japanese>char型の列にASCII以外の文字を渡した。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        ASCIIしか渡さないようにするか、列の型をncharにする。
      </Japanese>
    </Solution>
  </Error>

<!-- 22022 indicator overflow(1721) -->
<!-- 22023 invalid parameter value(1722) -->
<!-- 22024 unterminated C string(1723) -->

<!-- 22025 invalid escape sequence(1724) -->
  <Error>
    <Name>InvalidEscapeSequence</Name>
    <Number>0x10001724</Number>
    <StateCode>22025</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - invalid escape sequence.</English>
      <Japanese>LIKEのパターンにおけるエスケープ文字の使い方に誤りがあります。</Japanese>
    </Message>
    <Description>
      <Japanese>以下の条件を満たさなかった: likeのパターンが1文字か2文字の部分に分解できて、1文字の部分はエスケープ文字以外からなり、2文字の部分はエスケープ文字とエスケープ文字かアンダースコアかパーセント記号の連結である。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        エスケープ文字を正しく使う。
      </Japanese>
    </Solution>
  </Error>

<!-- 22027 trim error(1725) -->

<!-- 22029 noncharacter in UCS string(1726) -->
  <Error>
    <Name>NonCharacterInString</Name>
    <Number>0x10001726</Number>
    <StateCode>22029</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - noncharacter in UCS string.</English>
      <Japanese>文字列中にUCSの文字でないデータが含まれます。</Japanese>
    </Message>
    <Description>
      <Japanese>文字列中にUCSではないデータが含まれている。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        文字列の内容を確認する。
      </Japanese>
    </Solution>
  </Error>

<!-- 2202D null value substituted for mutator subject parameter(1727) -->

<!-- 2202E array element error(1728) -->
  <Error>
    <Name>BadArrayElement</Name>
    <Number>0x10001728</Number>
    <StateCode>2202E</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - array element error.</English>
      <Japanese>ARRAYの要素指定が不正です。</Japanese>
    </Message>
    <Description>
      <Japanese>ARRAYの要素指定が範囲外だった。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        要素指定を確認する。
      </Japanese>
    </Solution>
  </Error>

<!-- 2202F array data, right truncation(1729) -->
  <Error>
    <Name>ArrayRightTruncation</Name>
    <Number>0x10001729</Number>
    <StateCode>2202F</StateCode>
    <Level>User</Level>
    <Message>
      <English>Data exception - array data, right truncation.</English>
      <Japanese>ARRAYの代入で最大長を超える部分があります。</Japanese>
    </Message>
    <Description>
      <Japanese>ARRAYの代入で代入もとの要素数が代入先の最大長を超えていた。</Japanese>
    </Description>
    <Solution>
      <Japanese>
        代入もとの要素数が超えないように確認する。
      </Japanese>
    </Solution>
  </Error>

<!-- 2202G invalid repeat argument in a sample clause(172a) -->
<!-- 2202H invalid sample size(172b) -->

<!-- *************** SYSTEM DEFINED ****************** -->
<!-- 22501 can't cast class(1751) -->
  <Error>
    <Name>ClassCast</Name>
    <!-- v14以前からあるので番号は昔のものを使う -->
    <Number>0x00010002</Number>
    <StateCode>22501</StateCode>
    <Level>User</Level>
    <Message>
      <English>Can't cast class.</English>
      <Japanese>クラスのキャストに失敗しました。</Japanese>
    </Message>
    <Description>
      <Japanese>
	オブジェクトの内容を別のクラスにキャストしようとして失敗した
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	キャストが可能なクラスか確認し、
	データがキャスト可能でなければ正しいデータを与える
      </Japanese>
    </Solution>
  </Error>

<!-- 22502 invalid section data(1752) -->
  <Error>
    <Name>InvalidSectionData</Name>
    <Number>0x10001752</Number>
    <StateCode>22502</StateCode>
    <Level>User</Level>
    <Message>
      <English>Invalid section data.</English>
      <Japanese>セクションデータが異常です。</Japanese>
    </Message>
    <Description>
      <Japanese>
	全文索引に使うセクションデータと言語データの次数があっていない
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	全文索引に使うセクションデータと言語データの次数を合わせる
      </Japanese>
    </Solution>
  </Error>

 <!-- 22510 invalid data file format(1760) -->
  <Error>
    <Name>InvalidDataFile</Name>
    <Number>0x10001760</Number>
    <StateCode>22510</StateCode>
    <Level>User</Level>
    <Message>
      <English>Invalid data file format. (record #%1)</English>
      <Japanese>データファイルのフォーマットが不正です。(%1レコード目)</Japanese>
    </Message>
    <MessageArgument>%d</MessageArgument>
    <Description>
      <Japanese>INSERT INPUT FROM構文などで指定したデータファイルが規定のフォーマットに合わない</Japanese>
    </Description>
    <Solution>
      <Japanese>
        データファイルや構文に渡すHINTを見直す
      </Japanese>
    </Solution>
  </Error>
<!-- ************ END OF SYSTEM DEFINED ************** -->

<!-- 23 X integrity constraint violation(0x10001800) -->
<!-- 23000 (no subclass)(1801) -->

  <Error>
    <Name>IntegrityViolation</Name>
    <!-- v14以前からあるので昔の番号を使う -->
    <Number>0x00070001</Number>
    <StateCode>23000</StateCode>
    <Level>User</Level>
    <Message>
      <English>Integrity constraint violation.</English>
      <Japanese>インテグリティに違反するデータ操作を行おうとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>それを実行するとインテグリティを破ってしまうようなデータ操作を行おうとした</Japanese>
    </Description>
    <Solution>
      <Japanese>インテグリティに違反するデータ操作を行わない</Japanese>
    </Solution>
  </Error>

<!-- 23001 restrict violation(1802) -->

<!-- *************** SYSTEM DEFINED ****************** -->
<!-- 23501 nullablility violation(1851) -->
  <Error>
    <Name>NullabilityViolation</Name>
    <Number>0x10001851</Number>
    <StateCode>23501</StateCode>
    <Level>User</Level>
    <Message>
      <English>NOT NULL constraint violation on the column '%1'.</English>
      <Japanese>NOT NULLの制約がついている列%1にNULLの値を設定しようとしました。</Japanese>
    </Message>
    <MessageArgument>%s</MessageArgument>
    <Description>
      <Japanese>挿入または更新でNOT NULLの制約がついている列にNULLの値を設定しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>NOT NULLの列にNULLを入れない</Japanese>
    </Solution>
  </Error>

<!-- 23502 uniqueness violation(1852) -->
  <Error>
    <Name>UniquenessViolation</Name>
    <Number>0x10001852</Number>
    <StateCode>23502</StateCode>
    <Level>User</Level>
    <Message>
      <English>UNIQUE constraint violation.</English>
      <Japanese>UNIQUE制約に違反するデータ操作を行おうとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>UNIQUE制約に違反するデータ操作を行おうとした</Japanese>
    </Description>
    <Solution>
      <Japanese>UNIQUE制約に違反するデータ操作を行わない</Japanese>
    </Solution>
  </Error>

<!-- 23503 refered key violation(1853) -->
  <Error>
    <Name>ForeignKeyViolation</Name>
    <Number>0x10001853</Number>
    <StateCode>23003</StateCode>
    <Level>User</Level>
    <Message>
      <English>Integrity constraint violation - no matching row in foreign key.</English>
      <Japanese>外部キーに合致するレコードがありません。</Japanese>
    </Message>
    <Description>
      <Japanese>外部キーで参照しているレコードに存在しない値を設定しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>外部キーに存在する値を使用する</Japanese>
    </Solution>
  </Error>

<!-- 23504 refered key violation(1854) -->
  <Error>
    <Name>ReferedKeyViolation</Name>
    <Number>0x10001854</Number>
    <StateCode>23004</StateCode>
    <Level>User</Level>
    <Message>
      <English>Integrity constraint violation - referenced by foreign key.</English>
      <Japanese>外部キーで参照されている列を削除または更新しようとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>外部キーで参照されている列を削除または更新しようとした</Japanese>
    </Description>
    <Solution>
      <Japanese>外部キーで参照されている列は更新しない。または参照しているレコードから削除または更新する</Japanese>
    </Solution>
  </Error>

<!-- ************ END OF SYSTEM DEFINED ************** -->
		
<!-- 24 X invalid cursor state(0x10001900) -->

<!-- 25 X invalid transaction state(0x10001a00) -->

<!-- 25000 (no subclass)(1a01) -->
<!-- 25001 active SQL-transaction(1a02) -->
  <Error>
    <Name>AlreadyBeginTransaction</Name>
    <!-- v14以前からあるので昔の番号を使う -->
    <Number>0x00090001</Number>
    <StateCode>25001</StateCode>
    <Level>User</Level>
    <Message>
      <English>Active SQL-transaction.</English>
      <Japanese>すでにトランザクションは開始されています。</Japanese>
    </Message>
    <Description>
      <Japanese>
	トランザクション中にトランザクションを開始しようとした。または、トランザクションブランチを開始もしくは待機しようとした
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	トランザクションを開始しない
      </Japanese>
    </Solution>
  </Error>

<!-- 25002 branch transaction already active(1a03) -->
  <Error>
    <Name>XA_InsideActiveBranch</Name>
    <Number>0x00001a03</Number>
    <StateCode>25002</StateCode>
    <Level>User</Level>
    <Message>
      <English>Branch transaction already active.</English>
      <Japanese>すでにトランザクションブランチは開始されています。</Japanese>
    </Message>
    <Description>
      <Japanese>
	データ操作中のトランザクションブランチにおいて不可なトランザクション操作・トランザクションブランチ操作を行おうとした
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	不可な操作を行わない
      </Japanese>
    </Solution>
  </Error>

<!-- 25003 inappropriate access mode for branch transaction(1a04) -->
<!-- 25004 inappropriate isolation level for branch transaction(1a05) -->
<!-- 25005 no active SQL-transaction for branch transaction(1a06) -->
<!-- 25006 read-only SQL-transaction(1a07) -->
  <Error>
    <Name>ReadOnlyTransaction</Name>
    <!-- v14以前からあるので昔の番号を使う -->
    <Number>0x00090003</Number>
    <StateCode>25006</StateCode>
    <Level>User</Level>
    <Message>
      <English>Read-only SQL-transaction.</English>
      <Japanese>読み取り専用トランザクションで許されない操作を行おうとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>
	読み取り専用トランザクションで許されない操作を行おうとした
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	更新トランザクションで行う。
      </Japanese>
    </Solution>
  </Error>

<!-- 25007 schema and data statement mixing not supported(1a08) -->
<!-- 25008 held cursor requires same isolation level(1a09) -->

<!-- *************** SYSTEM DEFINED ****************** -->
<!-- 25501 schema statement in explicit transaction(1a51) -->
  <Error>
    <Name>InvalidExplicitTransaction</Name>
    <Number>0x10001a51</Number>
    <StateCode>25501</StateCode>
    <Level>User</Level>
    <Message>
      <English>Schema statement in explicit transaction.</English>
      <Japanese>明示的に開始されたトランザクション中にスキーマ操作を行おうとしました。</Japanese>
    </Message>
    <Description>
      <Japanese>
	明示的に開始されたトランザクション中にスキーマ操作を行おうとした
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	暗黙トランザクションで行う。
      </Japanese>
    </Solution>
  </Error>

<!-- 25502 not in transaction(1a52) -->
  <Error>
    <Name>NotBeginTransaction</Name>
    <Number>0x10001a52</Number>
    <StateCode>25502</StateCode>
    <Level>User</Level>
    <Message>
      <English>Not in transaction.</English>
      <Japanese>トランザクションが開始されていません。</Japanese>
    </Message>
    <Description>
      <Japanese>
	トランザクション中に行うべき処理をトランザクションを
	開始せずに行おうとした
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	トランザクションを開始する
      </Japanese>
    </Solution>
  </Error>

<!-- 25503 badtransaction(1a53) -->
  <Error>
    <Name>BadTransaction</Name>
    <!-- v14以前から昔の番号を使う -->
    <Number>0x00090004</Number>
    <StateCode>25503</StateCode>
    <Level>User</Level>
    <Message>
      <English>Transaction mode or isolation level is inconsistent with operation.</English>
      <Japanese>トランザクションの読み書き属性かアイソレーションレベルが行おうとした操作と両立しません。</Japanese>
    </Message>
    <Description>
      <Japanese>
	トランザクションの読み書き属性かアイソレーションレベルが行おうとした操作で許されていないものだった。
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	正しい読み書き属性およびアイソレーションレベルを持ったトランザクションで行う。
      </Japanese>
    </Solution>
  </Error>

<!-- 25504 duplicate transaction branch identifier(1a54) -->
  <Error>
    <Name>XA_DuplicateIdentifier</Name>
    <Number>0x00001a54</Number>
    <StateCode>25504</StateCode>
    <Level>User</Level>
    <Message>
      <English>Duplicate transaction branch identifier.</English>
      <Japanese>トランザクションブランチ識別子はすでに使用中です。</Japanese>
    </Message>
    <Description>
      <Japanese>
	『データ操作中』・『中断中』・『待機中』のトランザクションブランチのトランザクションブランチ識別子を指定して新たにトランザクションブランチを開始した。
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	トランザクションブランチ識別子が誤っていないか確認する。JOIN句またはRESUME句を指定してトランザクションブランチを合流または再開する。
      </Japanese>
    </Solution>
  </Error>

<!-- 25505 transaction branch statement protocol error(1a55) -->
  <Error>
    <Name>XA_ProtocolError</Name>
    <Number>0x00001a55</Number>
    <StateCode>25505</StateCode>
    <Level>User</Level>
    <Message>
      <English>Transaction branch statement protocol error.</English>
      <Japanese>トランザクションブランチに対する不正な操作です。</Japanese>
    </Message>
    <Description>
      <Japanese>
	ある状態のトランザクションブランチに対して許されない操作を行おうとした。
      </Japanese>
    </Description>
    <Solution>
      <Japanese>
	行おうとした操作が正しいか確認する。トランザクションブランチ識別子が誤っていないか確認する。
      </Japanese>
    </Solution>
  </Error>

<!-- 25506 unknown transaction branch identifier(1a56) -->
  <Error>
    <Name>XA_UnknownIdentifier</Name>